import { Article, Portfolio } from '../shared/types';
export const demo: Portfolio = {
  positions: [
    {
      id: 'nvda',
      symbol: 'NVDA',
      name: 'NVIDIA',
      assetClass: 'Stocks',
      currency: 'USD',
      units: 180,
      price: 142.87,
      value: 25716.6,
      cost: 18540,
      change: 2.84,
      color: '#b5e853',
      accounts: ['Fidelity'],
    },
    {
      id: 'voo',
      symbol: 'VOO',
      name: 'Vanguard S&P 500 ETF',
      assetClass: 'ETFs',
      currency: 'USD',
      units: 42,
      price: 562.18,
      value: 23611.56,
      cost: 20832,
      change: 0.68,
      color: '#f78e9d',
      accounts: ['Fidelity'],
    },
    {
      id: 'aapl',
      symbol: 'AAPL',
      name: 'Apple Inc.',
      assetClass: 'Stocks',
      currency: 'USD',
      units: 85,
      price: 237.49,
      value: 20186.65,
      cost: 16575,
      change: 1.24,
      color: '#ccd5e1',
      accounts: ['Fidelity', 'Schwab'],
    },
    {
      id: 'btc',
      symbol: 'BTC',
      name: 'Bitcoin',
      assetClass: 'Crypto',
      currency: 'USD',
      units: 0.18,
      price: 97842.16,
      value: 17611.5888,
      cost: 12960,
      change: 3.12,
      color: '#ffb45e',
      accounts: ['Coinbase'],
    },
    {
      id: 'msft',
      symbol: 'MSFT',
      name: 'Microsoft',
      assetClass: 'Stocks',
      currency: 'USD',
      units: 32,
      price: 428.76,
      value: 13720.32,
      cost: 11840,
      change: -0.42,
      color: '#83baff',
      accounts: ['Schwab'],
    },
    {
      id: 'eth',
      symbol: 'ETH',
      name: 'Ethereum',
      assetClass: 'Crypto',
      currency: 'USD',
      units: 3.2,
      price: 3248.92,
      value: 10396.544,
      cost: 8480,
      change: 1.86,
      color: '#b4a0f5',
      accounts: ['Coinbase'],
    },
    {
      id: 'bnd',
      symbol: 'BND',
      name: 'Vanguard Total Bond Market',
      assetClass: 'Bonds',
      currency: 'USD',
      units: 100,
      price: 73.82,
      value: 7382,
      cost: 7420,
      change: -0.08,
      color: '#66c9b3',
      accounts: ['Fidelity'],
    },
    {
      id: 'cash',
      symbol: 'USD',
      name: 'Cash & equivalents',
      assetClass: 'Cash',
      currency: 'USD',
      units: 4800,
      price: 1,
      value: 4800,
      cost: 4800,
      change: 0,
      color: '#97a59a',
      accounts: ['Fidelity'],
    },
  ],
  accounts: [
    { id: 'fidelity', name: 'Individual investing', institution: 'Fidelity' },
    { id: 'schwab', name: 'Long-term portfolio', institution: 'Schwab' },
    { id: 'coinbase', name: 'Crypto wallet', institution: 'Coinbase' },
  ],
  history: Array.from({ length: 181 }, (_, i) => ({
    date: new Date(Date.UTC(2026, 2, 29 + i)).toISOString().slice(0, 10),
    value:
      97700 +
      i * 235 +
      Math.sin(i * 0.19) * 2200 +
      Math.sin(i * 0.91) * 700 -
      (i > 90 && i < 118 ? Math.sin(((i - 90) / 28) * Math.PI) * 9000 : 0),
  })),
  favorites: ['nvda'],
  syncedAt: null,
  warnings: [],
};
const demoTotal = demo.positions.reduce((s, p) => s + (p.value ?? 0), 0);
const scale = demoTotal / demo.history[demo.history.length - 1].value;
demo.history = demo.history.map((point) => ({ ...point, value: point.value * scale }));
export const demoNews: Article[] = [
  {
    id: '1',
    title: 'The next chapter of the AI infrastructure buildout',
    source: 'Growth Editorial',
    publishedAt: '2026-09-25T12:00:00Z',
    category: 'Technology',
    symbols: ['NVDA', 'MSFT'],
    summary:
      'Sample story · Explore how demand for accelerated computing could shape the companies in your portfolio.',
  },
  {
    id: '2',
    title: 'Bitcoin and the changing landscape of institutional adoption',
    source: 'Growth Editorial',
    publishedAt: '2026-09-25T10:00:00Z',
    category: 'Crypto',
    symbols: ['BTC', 'ETH'],
    summary:
      'Sample story · A closer look at the themes moving digital assets and the broader market.',
  },
  {
    id: '3',
    title: 'What a shift in interest rates means for a balanced portfolio',
    source: 'Growth Editorial',
    publishedAt: '2026-09-24T15:00:00Z',
    category: 'Macro',
    symbols: ['BND', 'VOO'],
    summary:
      'Sample story · Bonds, equities, and the relationship between them. The context behind your allocation.',
  },
  {
    id: '4',
    title: 'Beyond the launch: the long view on Apple’s ecosystem',
    source: 'Growth Editorial',
    publishedAt: '2026-09-24T13:00:00Z',
    category: 'Technology',
    symbols: ['AAPL'],
    summary:
      'Sample story · Services, devices, and the recurring revenue story behind a familiar holding.',
  },
];
